export enum Status {
  NEW = 'NEW',
  COMPLETED = 'COMPLETED',
  SKIPPED = 'SKIPPED',
  PENDING = 'PENDING',
  INCOMPLETE = 'INCOMPLETE',
}

export enum QuestionType {
  RADIO_BUTTON_TEXT = 'RADIO_BUTTON_TEXT',
  CHECKBOX_BUTTON_TEXT = 'CHECKBOX_BUTTON_TEXT',
  INPUT_TEXT = 'INPUT_TEXT',
  DROP_DOWN = 'DROP_DOWN',
  INTEGER = 'INTEGER',
}

export enum State {
  GOAL_DEFINATION = 'GOAL_DEFINATION',
  RISK_PROFILE = 'RISK_PROFILE',
  FINANCIAL_SUITABILITY = 'FINANCIAL_SUITABILITY',
  FINANCIAL_CALCULATIONS = 'FINANCIAL_CALCULATIONS',
  INVESTMENTS_STRATEGY = 'INVESTMENTS_STRATEGY',
  USER_INVESTMENTS = 'USER_INVESTMENTS',
  USER_PORTFOLIO = 'USER_PORTFOLIO',
}

export enum LogLevel {
  Debug = 'DEBUG',
  Info = 'INFO',
  Warn = 'WARN',
  Error = 'ERROR',
}