name: Build Docker and Push

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  HARBOR_REGISTRY: harbor.humancloud.ltd
  HARBOR_PROJECT: gbs
  IMAGE_NAME: dev-frontend

jobs:
  build-and-push:
    runs-on: self-hosted
    outputs:
      image_tag: ${{ steps.set-image-tag.outputs.IMAGE_TAG }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Image Tag (Commit Hash)
        id: set-image-tag
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Login to Harbor
        run: echo "${{ secrets.HARBOR_PASSWORD }}" | docker login $HARBOR_REGISTRY -u "${{ secrets.HARBOR_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          docker build -t $HARBOR_REGISTRY/$HARBOR_PROJECT/$IMAGE_NAME:$IMAGE_TAG .
          docker push $HARBOR_REGISTRY/$HARBOR_PROJECT/$IMAGE_NAME:$IMAGE_TAG

  update-k8s-manifest:
    name: Update K8s Manifest in Internal Deployment Repo
    runs-on: self-hosted
    needs: build-and-push
    env:
      IMAGE_TAG: ${{ needs.build-and-push.outputs.image_tag }}

    steps:
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_RUNNER_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Checkout Internal Deployment Repo
        uses: actions/checkout@v4
        with:
          repository: humancloud/hct_deployment_internal
          ssh-key: ${{ secrets.SSH_RUNNER_KEY }}
          ref: main

      - name: Update Image Tag in GBS/frontend.yml
        run: |
          sed -i 's|image: harbor.humancloud.ltd/gbs/dev-frontend:.*|image: harbor.humancloud.ltd/gbs/dev-frontend:${{ env.IMAGE_TAG }}|' GBS/frontend.yml

      - name: Commit and Push Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git add GBS/frontend.yml
          git commit -m "Update gbs-frontend image tag to ${{ env.IMAGE_TAG }}"
          git push origin main
