name: Build and Push to Docker Hub!

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: sanu1915/gbs-frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Commit Hash as Image Tag
        id: tag
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t $IMAGE_NAME:${{ steps.tag.outputs.IMAGE_TAG }} . --no-cache
          docker push $IMAGE_NAME:${{ steps.tag.outputs.IMAGE_TAG }}

